import React from "react";
import { SectionHeader } from "../components/SectionHeader";
import { Icon, ICONS } from "../components/Icons";

export function AiAnalysis({
  assessmentForm = { department: "", symptom: "", severity: "" },
  onAssessmentFormChange,
  aiResult,
  aiLoading,
  getAIAnalysis,
  onClearResult,
}) {
  return (
    <div className="space-y-6 animate-fade-in-up">
      {/* Input Form Card */}
      <div className="glass rounded-2xl p-6">
        <SectionHeader
          icon={ICONS.brain}
          title="AI-Powered Triage Analysis"
          subtitle="Powered by Google Gemini 2.5 Flash — input symptoms and severity below"
        />
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5">
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-slate-400 uppercase tracking-wider">Department</label>
            <select
              id="ai-dept"
              className="field cursor-pointer"
              value={assessmentForm.department}
              onChange={(e) => onAssessmentFormChange({ ...assessmentForm, department: e.target.value })}
            >
              <option value="">Select Department</option>
              <option>Orthopedics</option>
              <option>Dermatology</option>
              <option>ENT</option>
              <option>Neurology</option>
              <option>Cardiology</option>
              <option>General Medicine</option>
            </select>
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-slate-400 uppercase tracking-wider">Symptom</label>
            <input
              id="ai-symptom"
              className="field"
              type="text"
              placeholder="Describe symptom…"
              value={assessmentForm.symptom}
              onChange={(e) => onAssessmentFormChange({ ...assessmentForm, symptom: e.target.value })}
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-slate-400 uppercase tracking-wider">Severity</label>
            <select
              id="ai-severity"
              className="field cursor-pointer"
              value={assessmentForm.severity}
              onChange={(e) => onAssessmentFormChange({ ...assessmentForm, severity: e.target.value })}
            >
              <option value="">Select Severity</option>
              <option>Mild</option>
              <option>Moderate</option>
              <option>Severe</option>
            </select>
          </div>
        </div>
        <button
          id="run-ai-btn"
          onClick={getAIAnalysis}
          disabled={aiLoading}
          className="btn-primary cursor-pointer"
          style={{ opacity: aiLoading ? 0.7 : 1 }}
        >
          {aiLoading ? (
            <>
              <span className="spinner" />
              <span>Analyzing…</span>
            </>
          ) : (
            <>
              <Icon d={ICONS.brain} size={15} />
              <span>Run AI Analysis</span>
            </>
          )}
        </button>
      </div>

      {/* AI Result Card */}
      {aiResult && (
        <div
          className="glass rounded-2xl p-6 animate-fade-in-up"
          style={{
            border: "1px solid rgba(99,102,241,0.25)",
            boxShadow: "0 0 40px rgba(99,102,241,0.08)",
          }}
        >
          <div className="flex items-center gap-3 mb-5">
            <div
              className="w-10 h-10 rounded-xl flex items-center justify-center"
              style={{
                background: "linear-gradient(135deg,#6366f1,#8b5cf6)",
                boxShadow: "0 0 20px rgba(99,102,241,0.4)",
              }}
            >
              <Icon d={ICONS.brain} size={18} className="text-white" />
            </div>
            <div>
              <p className="font-bold text-white text-sm">AI Recommendation</p>
              <p className="text-xs text-slate-500">Generated by Gemini 2.5 Flash</p>
            </div>
            <button onClick={onClearResult} className="ml-auto text-slate-500 hover:text-white cursor-pointer">
              <Icon d={ICONS.xmark} size={16} />
            </button>
          </div>
          <div
            className="rounded-xl p-5 whitespace-pre-wrap text-sm leading-relaxed text-slate-300"
            style={{
              background: "rgba(99,102,241,0.06)",
              border: "1px solid rgba(99,102,241,0.1)",
              fontFamily: "inherit",
            }}
          >
            {aiResult}
          </div>
        </div>
      )}

      {!aiResult && !aiLoading && (
        <div className="flex flex-col items-center justify-center py-16 text-slate-600">
          <div
            className="w-16 h-16 rounded-2xl flex items-center justify-center mb-4"
            style={{
              background: "rgba(99,102,241,0.08)",
              border: "1px solid rgba(99,102,241,0.1)",
            }}
          >
            <Icon d={ICONS.brain} size={28} />
          </div>
          <p className="text-sm font-medium">No analysis yet</p>
          <p className="text-xs mt-1 text-slate-700">Fill in the fields above and click "Run AI Analysis"</p>
        </div>
      )}
    </div>
  );
}
